---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

after_success:
    "curl --ftp-create-dirs -T \"dist/\" -u $FTP_USER:$FTP_PASSWORD ftp://5.100.228.185/home/deploy/www/demo"
after_failure:
    "curl --ftp-create-dirs -T \"dist/\" -u $FTP_USER:$FTP_PASSWORD ftp://5.100.228.185/home/deploy/www/demo"
