---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

after_success:
  - ember build --environment=production
  - curl -T "dist/index.html" -u $FTP_USER:$FTP_PASSWORD ftp://5.100.228.185/www/demo/
  - cd dist/assets ; for i in * ; do curl -T "$i" -u $FTP_USER:$FTP_PASSWORD ftp://5.100.228.185/www/demo/assets/$i ; done ; cd ../..
after_failure:
  - ember build
  - curl -T "dist/index.html" -u $FTP_USER:$FTP_PASSWORD ftp://5.100.228.185/www/demo/
  - cd dist/assets ; for i in * ; do curl -T "$i" -u $FTP_USER:$FTP_PASSWORD ftp://5.100.228.185/www/demo/assets/$i ; done ; cd ../..
